package xianjue.gqx.po;

// Generated 2015-5-28 15:52:36 by Hibernate Tools 4.0.0

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Gprs generated by hbm2java
 */
@Entity
@Table(name = "gprs")
public class Gprs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column
	@GeneratedValue
	private Integer id;
	@Column
	private String name;
	@Column
	private String mac;
	@Column
	private String ip;
	@Column
	private Integer illumination;
	@Column
	private Integer temperature;
	@Column
	private Integer humidity;
	@Column
	private String state;
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column
	private Timestamp update_time;

	public Gprs() {
	}

	public Gprs(Timestamp update_time) {
		this.update_time = update_time;
	}

	public Gprs(String name, String mac, String ip, Integer illumination,
			Integer temperature, Integer humidity, Timestamp update_time) {
		this.name = name;
		this.mac = mac;
		this.ip = ip;
		this.illumination = illumination;
		this.temperature = temperature;
		this.humidity = humidity;
		this.update_time = update_time;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Integer getIllumination() {
		return this.illumination;
	}

	public void setIllumination(Integer illumination) {
		this.illumination = illumination;
	}

	public Integer getTemperature() {
		return this.temperature;
	}

	public void setTemperature(Integer temperature) {
		this.temperature = temperature;
	}

	public Integer getHumidity() {
		return this.humidity;
	}

	public void setHumidity(Integer humidity) {
		this.humidity = humidity;
	}

	public Timestamp getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Timestamp update_time) {
		this.update_time = update_time;
	}


}
