package xianjue.gqx.po;

// Generated 2015-6-1 19:50:59 by Hibernate Tools 4.0.0

import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Historydata generated by hbm2java
 */
@Entity
@Table(name = "Historydata")
public class Historydata implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column
	@GeneratedValue
	private Integer id;
	@Column
	private Integer gid;
	@Column
	private Integer illumination;
	@Column
	private Integer temperature;
	@Column
	private Integer humidity;
	@Column
	private Timestamp update_time;

	public Historydata() {
	}

	public Historydata(Timestamp update_time) {
		this.update_time = update_time;
	}

	public Historydata(Integer gid, Integer illumination, Integer temperature,
			Integer humidity, Timestamp update_time) {
		this.gid = gid;
		this.illumination = illumination;
		this.temperature = temperature;
		this.humidity = humidity;
		this.update_time = update_time;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	public Integer getIllumination() {
		return this.illumination;
	}

	public void setIllumination(Integer illumination) {
		this.illumination = illumination;
	}

	public Integer getTemperature() {
		return this.temperature;
	}

	public void setTemperature(Integer temperature) {
		this.temperature = temperature;
	}

	public Integer getHumidity() {
		return this.humidity;
	}

	public void setHumidity(Integer humidity) {
		this.humidity = humidity;
	}

	public Timestamp getUpdateTime() {
		return this.update_time;
	}

	public void setUpdateTime(Timestamp update_time) {
		this.update_time = update_time;
	}

}
