package xianjue.gqx.po;

// Generated 2015-5-28 15:52:36 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WaterValve generated by hbm2java
 */
@Entity
@Table(name = "Water_valve")
public class WaterValve implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column
	@GeneratedValue
	private Integer id;
	@Column
	private Integer gid;
	@Column
	private String name;
	@Column
	private Integer gorder;
	@Column
	private int state;
	@Column
	private Date updateTime;

	public WaterValve() {
	}

	public WaterValve(int state, Date updateTime) {
		this.state = state;
		this.updateTime = updateTime;
	}

	public WaterValve(Integer gid, String name, Integer gorder, int state,
			Date updateTime) {
		this.gid = gid;
		this.name = name;
		this.gorder = gorder;
		this.state = state;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getGorder() {
		return gorder;
	}

	public void setGorder(Integer gorder) {
		this.gorder = gorder;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
